//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Ткани.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string ProductId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryData { get; set; }
        public int PointId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Code { get; set; }
        public int StatusId { get; set; }
        public int Count { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
